[HOME-2] Categories
KatarzynaWolowska/08-ecommerce-nextjs pull request #2
Opened 2023-11-21 20:50 UTC by KatarzynaWolowska

2023-11-27 12:02 UTC, mkokosinski requested changes

2023-11-27 12:02 UTC, mkokosinski commented on components/Banners/TopBanner.module.scss
> +    .column {
tą poprawkę zrób na innym branchu

2023-11-27 12:02 UTC, mkokosinski commented on components/Button/Button.module.scss
> +        transition: all 400ms ease-out;
do usunięcia, masz tą samą linijkę na tagu button

2023-11-27 12:02 UTC, mkokosinski commented on components/Categories/Categories.module.scss
> +            padding-top: 110px;
zrób to jako bg, i usuń usjemne margin-top

2023-11-27 12:02 UTC, mkokosinski commented on components/Categories/Categories.module.scss
> +            button {
klasa zamiast button

2023-11-27 12:02 UTC, mkokosinski commented on components/Categories/CategoryList.jsx
> +        { title: 'Headphones', href: './headphones', image: Headphones },
sprawdź czy ta kropka jest wymagana

2023-11-27 12:02 UTC, mkokosinski commented on styles/fonts.scss
> +@media (max-width: breakpoints.$breakpoint-tablet) {
zmień na mobile-first

2023-11-28 13:43 UTC, KatarzynaWolowska commented on components/Categories/CategoryList.jsx
> +        { title: 'Headphones', href: './headphones', image: Headphones },
niepotrzebne :)
https://nextjs.org/learn-pages-router/basics/navigate-between-pages/link-component

2023-11-28 14:04 UTC, KatarzynaWolowska commented on styles/fonts.scss
> +@media (max-width: breakpoints.$breakpoint-tablet) {
dam w osobnym tasku https://trello.com/c/Gq96y2ZP/35-fix-fonts-mobile-first

2023-11-29 13:28 UTC, mkokosinski approved these changes

2023-11-29 13:28 UTC, merged